## ======================================================================
## Pipeline for GPDB PL/R GPPKG
## ======================================================================

groups:
- name: ALL
  jobs:
    - diskquota_centos6_build_test
    - diskquota_centos7_build_test
    - diskquota_ubuntu18_build_test
    - diskquota_centos7_extension_upgrade_1.0_2.0
- name: GPDB6
  jobs:
    - diskquota_centos6_build_test
    - diskquota_centos7_build_test
    - diskquota_rhel8_build_test
    - diskquota_ubuntu18_build_test
- name: GPDB6_UPGRADE
  jobs:
    - diskquota_centos7_extension_upgrade_1.0_2.0

resource_types:
- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:

# Image Resources

- name: centos-gpdb-dev-6
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb5-centos6-build-test
    tag: latest

- name: centos-gpdb-dev-7
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb5-centos7-build-test
    tag: latest

- name: rhel-image-dev-8
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb6-rhel8-test
    tag: latest
    username: _json_key
    password: ((container-registry-readonly-service-account-key))

- name: rhel-image-build-8
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-private-images/gpdb6-rhel8-build
    tag: latest
    username: _json_key
    password: ((container-registry-readonly-service-account-key))

- name: ubuntu18-image-build
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-ubuntu18.04-build
    tag: latest

- name: ubuntu18-image-test
  type: registry-image
  source:
    repository: gcr.io/data-gpdb-public-images/gpdb6-ubuntu18.04-test
    tag: latest

- name: bin_diskquota_centos7_1.0
  type: gcs
  source:
    bucket: {{gcs-bucket}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    regexp: diskquota/released/gpdb6/diskquota-(1.*)-rhel7_x86_64.tar.gz

- name: bin_diskquota_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket-dev}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: diskquota/intermediates/gpdb6/diskquota-master-rhel7_x86_64.tar.gz

# Github Source Codes

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}

- name: diskquota_src
  type: git
  source:
    branch: gpdb
    uri: https://github.com/greenplum-db/diskquota.git

# gpdb binary on gcs is located as different folder for different version
# use gcs_gpdb_binary_folder to specify them.
- name: bin_gpdb_centos6
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_centos6/bin_gpdb.tar.gz
- name: bin_gpdb_rhel8
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_rhel8/bin_gpdb.tar.gz
- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_centos7/bin_gpdb.tar.gz
- name: bin_gpdb_ubuntu18
  type: gcs
  source:
    bucket: {{gcs-bucket-intermediates}}
    json_key: {{concourse-gcs-resources-service-account-key}}
    versioned_file: ((gcs_gpdb_binary_folder))/bin_gpdb_ubuntu18.04/bin_gpdb.tar.gz

## jobs
## ======================================================================

jobs:
- name: diskquota_centos7_build_test
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: diskquota_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: gpdb_src
  - task: build_diskquota
    file: diskquota_src/concourse/tasks/build_diskquota.yml
    image: centos-gpdb-dev-7
    params:
      DISKQUOTA_OS: rhel7
  - task: test_diskquota
    file: diskquota_src/concourse/tasks/test_diskquota.yml
    image: centos-gpdb-dev-7
    input_mapping:
      bin_diskquota: diskquota_artifacts
    params:
      DISKQUOTA_OS: rhel7
  - aggregate:
    - put: bin_diskquota_centos7
      params:
        file: diskquota_artifacts/diskquota*.tar.gz

- name: diskquota_rhel8_build_test
  max_in_flight: 3
  plan:
  - aggregate:
    - get: rhel-image-dev-8
    - get: rhel-image-build-8
    - get: diskquota_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_rhel8
    - get: gpdb_src
  - task: build_diskquota
    file: diskquota_src/concourse/tasks/build_diskquota.yml
    image: rhel-image-build-8
    params:
      DISKQUOTA_OS: rhel8
  - task: test_diskquota
    file: diskquota_src/concourse/tasks/test_diskquota.yml
    image: rhel-image-dev-8
    input_mapping:
      bin_diskquota: diskquota_artifacts
    params:
      DISKQUOTA_OS: rhel8

- name: diskquota_centos6_build_test
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: diskquota_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: gpdb_src
  - task: build_diskquota
    file: diskquota_src/concourse/tasks/build_diskquota.yml
    image: centos-gpdb-dev-6
    params:
      DISKQUOTA_OS: rhel6
  - task: test_diskquota
    file: diskquota_src/concourse/tasks/test_diskquota.yml
    image: centos-gpdb-dev-6
    input_mapping:
      bin_diskquota: diskquota_artifacts
    params:
      DISKQUOTA_OS: rhel6

- name: diskquota_ubuntu18_build_test
  max_in_flight: 3
  plan:
  - aggregate:
    - get: ubuntu18-image-build
    - get: ubuntu18-image-test
    - get: diskquota_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
    - get: gpdb_src
  - task: build_diskquota
    file: diskquota_src/concourse/tasks/build_diskquota.yml
    image: ubuntu18-image-build
    params:
      DISKQUOTA_OS: ubuntu18.04
  - task: test_diskquota
    file: diskquota_src/concourse/tasks/test_diskquota.yml
    image: ubuntu18-image-test
    input_mapping:
      bin_diskquota: diskquota_artifacts
    params:
      DISKQUOTA_OS: ubuntu18.04

- name: diskquota_centos7_extension_upgrade_1.0_2.0
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: bin_diskquota_old
      resource: bin_diskquota_centos7_1.0
    - get: bin_diskquota_centos7
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: gpdb_src
    - get: diskquota_src
  - task: upgrade_extension
    file: diskquota_src/concourse/tasks/upgrade_extension.yml
    input_mapping:
      bin_diskquota_new: bin_diskquota_centos7
    image: centos-gpdb-dev-7
    params:
      DISKQUOTA_OS: rhel7
      OLD_VERSION: "1.0"
      NEW_VERSION: "2.0"
