#@ load("job_def.lib.yml",
#@   "build_test_job",
#@   "centos7_gpdb6_conf",
#@ )
#@ load("trigger_def.lib.yml",
#@   "pr_trigger",
#@ )
#@ load("base.lib.yml",
#@   "declare_res",
#@  "declare_res_type")
#@ res_map = {}
#@ res_type_map = {}
#@ job_param = {
#@   "res_map": res_map,
#@   "gpdb_src": "gpdb6_src",
#@   "trigger": pr_trigger(res_map),
#@   "confs": [centos7_gpdb6_conf()]
#@ }
jobs:
- #@ build_test_job(job_param)

resources: #@ declare_res(res_type_map, res_map)

resource_types: #@ declare_res_type(res_type_map)
