platform: linux
image_resource:
  type: docker-image
inputs:
  - name: bin_gpdb
  - name: bin_diskquota_old
  - name: bin_diskquota_new
  - name: gpdb_src
  - name: diskquota_src

run:
  path: diskquota_src/concourse/scripts/upgrade_extension.sh
params:
  DISKQUOTA_OS:
  OLD_VERSION:
  NEW_VERSION:
