#ifndef TOC_MAP
#define TOC_MAP

#define TableSizeMapNamePrefix "TableSizeMap"
#define QuotaInfoMapNamePrefix "QuotaInfoMap"

typedef enum
{
	TABLE_SIZE_MAP,
	QUOTA_INFO_MAP,
} HashMapType;

typedef struct HashMap
{
	/*
	 * The hash map name is generated by name prefix and database oid,
	 * and it will be used as the name of `HTAB *map`.
	 */
	char  name[NAMEDATALEN];
	HTAB *map;
} HashMap;

extern HTAB    *init_toc_map(void);
extern HashMap *search_toc_map(HTAB *toc_map, HashMapType type, Oid dbid);

#endif
